"use client";
import { useMemo, useState } from "react";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { SearchBar } from "@/components/SearchBar";
import { Sidebar } from "@/components/Sidebar";
import { SoundCard } from "@/components/SoundCard";
import type { Sound } from "@/lib/supabase";

export default function Library({ sounds }: { sounds: Sound[] }) {
  const [category, setCategory] = useState("all");
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => sounds.filter((s) => (category === "all" || s.category.toLowerCase() === category) && `${s.title} ${s.category} ${s.source}`.toLowerCase().includes(query.toLowerCase())), [sounds, category, query]);
  return <div className="studio-bg min-h-screen"><Navbar /><main className="mx-auto flex max-w-[1440px] flex-col gap-8 px-5 py-8 lg:flex-row lg:px-10 lg:py-12"><Sidebar active={category} onChange={setCategory} /><section className="min-w-0 flex-1"><div className="mb-8 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.24em] text-cyan-300"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_10px_#67e8f9]" /> Sound library / 001</p><h1 className="max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">The right sound makes<br /><span className="gradient-text">the cut feel alive.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-zinc-500">Copyright safe sounds for editors, creators, and storytellers. Preview, grab, and get back to your timeline.</p></div><div className="flex shrink-0 gap-8"><div><p className="text-2xl font-bold">{sounds.length}</p><p className="text-[10px] uppercase tracking-widest text-zinc-600">Sounds indexed</p></div><div><p className="text-2xl font-bold text-cyan-300">100%</p><p className="text-[10px] uppercase tracking-widest text-zinc-600">Clear licensing</p></div></div></div><SearchBar value={query} onChange={setQuery} /><div className="mb-5 mt-8 flex items-center justify-between"><div><h2 className="text-lg font-bold">{category === "all" ? "All sounds" : `${category[0].toUpperCase()}${category.slice(1)} sounds`}</h2><p className="mt-1 text-xs text-zinc-600">{filtered.length} results ready to use</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-zinc-500">Newest first</span></div>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((sound) => <SoundCard key={sound.id} sound={sound} />)}</div> : <div className="glass noise rounded-2xl px-6 py-20 text-center"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-white/5 text-zinc-600">◌</div><h3 className="font-bold">Your library is ready for its first session</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-600">Connect Supabase and run the seeder to populate ZOUND with real Freesound previews.</p><code className="mt-5 inline-block rounded-lg bg-black/30 px-3 py-2 text-xs text-cyan-300">npm run seed</code></div>}</section></main><Footer /></div>;
}
