"use client";
import { useEffect, useRef, useState } from "react";
import { Check, Copy, Download, Pause, Play, Radio } from "lucide-react";
import type { Sound } from "@/lib/supabase";

function formatDuration(seconds: number) { const s = Math.round(seconds || 0); return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`; }
export function SoundCard({ sound }: { sound: Sound }) {
  const audio = useRef<HTMLAudioElement>(null); const [playing, setPlaying] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { const el = audio.current; if (!el) return; const end = () => setPlaying(false); el.addEventListener("ended", end); return () => el.removeEventListener("ended", end); }, []);
  const toggle = () => { if (!audio.current) return; if (playing) audio.current.pause(); else audio.current.play().catch(() => setPlaying(false)); setPlaying(!playing); };
  const attribution = `${sound.title} by ${sound.source} — ${sound.license_type}`;
  const copy = async () => { await navigator.clipboard?.writeText(attribution); setCopied(true); setTimeout(() => setCopied(false), 1600); };
  return <article className="group glass rounded-2xl p-4 transition duration-300 hover:-translate-y-1 hover:border-purple-300/30 hover:shadow-2xl hover:shadow-purple-950/30"><div className="mb-5 flex items-start justify-between"><div className="flex items-center gap-3"><button onClick={toggle} aria-label={playing ? `Pause ${sound.title}` : `Play ${sound.title}`} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl gradient-line text-white shadow-lg shadow-purple-900/20 transition hover:scale-105">{playing ? <Pause size={19} fill="currentColor" /> : <Play size={19} fill="currentColor" className="ml-0.5" />}</button><div className="min-w-0"><h3 className="truncate text-sm font-bold text-zinc-100">{sound.title}</h3><p className="mt-1 text-xs text-zinc-500">{sound.category} · {formatDuration(sound.duration)}</p></div></div><span className="rounded-full border border-cyan-300/15 bg-cyan-300/10 px-2 py-1 text-[9px] font-bold tracking-wider text-cyan-200">{sound.license_type}</span></div><div className="mb-4 flex h-10 items-end gap-1 rounded-lg bg-black/20 px-3 py-2">{Array.from({ length: 28 }, (_, i) => <span key={i} className={`w-full rounded-full bg-gradient-to-t from-purple-500/50 to-cyan-300/80 transition ${playing ? "eq-bar" : "opacity-35"}`} style={{ height: `${20 + ((i * 17) % 65)}%`, animationDelay: `${i * .035}s` }} />)}</div><div className="flex items-center justify-between border-t border-white/5 pt-3"><span className="flex items-center gap-1.5 text-[11px] text-zinc-600"><Radio size={11} /> {sound.source || "Freesound"}</span><div className="flex gap-1"><button onClick={copy} title="Copy attribution" className="rounded-lg p-2 text-zinc-500 hover:bg-white/10 hover:text-white">{copied ? <Check size={15} /> : <Copy size={15} />}</button><a href={sound.file_url} download target="_blank" rel="noreferrer" title="Download preview" className="rounded-lg p-2 text-zinc-500 hover:bg-white/10 hover:text-white"><Download size={15} /></a></div></div><audio ref={audio} src={sound.file_url} preload="none" /></article>;
}
